### ISSUE TITLE
Homepage link buzuk 

### ISSUE THREAD

**Issue by nha** [p19y/onfaitlescourses.com#1]
The link on the HP to https://buzuk.bzh/ doesn't load

![Screenshot_20230127-214955](https://user-images.githubusercontent.com/1968291/215185296-cdf3037a-b2a2-4df3-94bf-672b52a0aac8.png)

**Comment by p19y** [comment]
https://buzuk.bzh/ doesn't load because shit happes, https://www.buzuk.bzh/ is better.

Thanks !
